// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function MoveDir(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function ReturnDir(arg1:Array<string>):Promise<string>;

export function ReturnDirItems(arg1:Array<string>):Promise<Array<main.File>>;
