// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePathURL(arg1) {
  return window['go']['main']['App']['GetFilePathURL'](arg1);
}

export function MoveDir(arg1, arg2) {
  return window['go']['main']['App']['MoveDir'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReturnDir(arg1) {
  return window['go']['main']['App']['ReturnDir'](arg1);
}

export function ReturnDirItems(arg1) {
  return window['go']['main']['App']['ReturnDirItems'](arg1);
}
